import Navbar from "@/components/Navbar";
import Provider from "@/components/Provider";
import ThemeProvider from "@/components/theme/ThemeProvider";
import { Toaster } from "@/components/ui/Toaster";
import { cn } from "@/lib/utils";
import "@/styles/globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next Auth",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={` ${cn(inter.className)}`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {/* Session provider */}
          <Provider>
            <Navbar />
            <div className="container h-[90vh] ">{children}</div>
          </Provider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
